version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /project/app
    depends_on:
      - db
